---
# Install Tuleap prerequisites

- name: Check SELinux policy
  command: getenforce
  register: se_status
  failed_when: "se_status.stdout not in ('Disabled', 'Permissive')"

- name: Setup epel
  yum: name=epel-release state="{{ tuleap_packages_state }}"

- name: Setup SCL repositories
  yum: name=centos-release-scl state="{{ tuleap_packages_state }}"

- name: Setup remi repositories
  yum: name="{{ remi_repo_base_url }}/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm" state="{{ tuleap_packages_state }}"

- name: Install prerequisite packages
  yum:
    name: ['rh-mysql57-mysql-server']
    state: "{{ tuleap_packages_state }}"

- name: Configure mysql
  copy:
    src: tuleap-mysql.cnf
    dest: /etc/opt/rh/rh-mysql57/my.cnf.d
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Start mysql
  service:
    name: rh-mysql57-mysqld
    state: started
    enabled: true
