#
# Tuleap install pre-requisites

- name: Setup epel
  yum: name=epel-release state="{{tuleap_packages_state}}"

- name: Install pre-requistes packages
  yum: name="{{item}}" state="{{tuleap_packages_state}}"
  with_items:
   - php-pecl-apc
   - mysql-server

- name: Start mysql
  service: name=mysqld state=started
