---
# Main Tuleap task list

- name: Gather installed packages
  package_facts:
    manager: auto

- include: selinux.yml
- include: repositories.yml
- include: tuleap_packages.yml
- include: mail-server.yml

- include: firewalld.yml
  when: "'firewalld' in ansible_facts.packages"

- name: Check if this is a new Tuleap install
  stat: path=/etc/tuleap/conf/local.inc
  register: tuleap_conf_file

- include: install.yml
  when: tuleap_conf_file.stat.exists == False

- include: letsencrypt_cert.yml