---
# Main Tuleap task list

- name: Check the OS major version
  fail:
    msg: "This tool supports only RedHat/CentOS after version 5. You use {{ ansible_os_family }} {{ ansible_distribution_major_version }}."
  when: ansible_os_family != "RedHat" or ansible_distribution_major_version|int <= 5

- include: dependencies.yml

- include: packages.yml

- name: Check if this is a new Tuleap install
  stat: path=/etc/tuleap/conf/local.inc
  register: tuleap_conf_file

- include: setup.yml
  when: tuleap_conf_file.stat.exists == False
