---
# Main Tuleap task list
- include_vars: "{{ tuleap_version }}.yml"

- include: dependencies.yml

- include: packages.yml

- name: Check if this is a new Tuleap install
  stat: path=/etc/tuleap/conf/local.inc
  register: tuleap_conf_file

- include: setup.yml
  when: tuleap_conf_file.stat.exists == False

- include: security.yml

- include: mail-server.yml
