---
# tasks file for tuleap
- include_vars: "{{ tuleap_version }}.yml"

- include: dependencies.yml

- include: packages.yml

- stat: path=/etc/tuleap/conf/local.inc
  register: tuleap_conf_file
  tags:
    - tuleap-update
    - tuleap-install

- include: install.yml
  when: tuleap_conf_file.stat.exists == False
  tags:
    - tuleap-install

- include: update.yml
  when: tuleap_conf_file.stat.exists == True
  tags: 
    - tuleap-update
