---
# Install Tuleap RPMs

- name: Install Tuleap repository
  template:
    src:   tuleap.repo.j2
    dest:  /etc/yum.repos.d/tuleap.repo
    owner: root
    group: root
    mode:  0644

- name: Install Tuleap
  yum:
    name: "{{ tuleap_packages|join(', ') }}"
    state: "{{ tuleap_packages_state }}"
    update_cache: yes
  notify:
    - forgeupgrade
    - restart apache
    - restart nginx
    - restart tuleap
