---
# Install Tuleap prerequisites

- name: Setup dependencies repositories
  yum: 
    name:
      - epel-release
      - centos-release-scl
      - https://rpms.remirepo.net/enterprise/remi-release-7.rpm  
    state: "{{ tuleap_packages_state }}"

- name: Install Tuleap repository
  copy:
    src: tuleap.repo
    dest: /etc/yum.repos.d/tuleap.repo
    owner: root
    group: root
    mode:  0644