---
# Install Tuleap prerequisites

- name: Setup dependencies repositories
  yum: 
    name:
      - epel-release
      - centos-release-scl
      - https://rpms.remirepo.net/enterprise/remi-release-7.rpm  
      - https://ci.tuleap.net/yum/tuleap/rhel/7/dev/x86_64/tuleap-community-release.rpm
    state: "{{ tuleap_packages_state }}"
