- name: Setup firewall for https
  firewalld:
    service: https
    permanent: yes
    state: enabled

- name: Setup firewall for http
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: Install Certbot (let's encrypt SSL certificate process)
  yum: 
    name: certbot, python2-certbot-nginx
    state: latest

- name: Request certificate
  command: /usr/bin/certbot --nginx certonly -d {{ tuleap_fqdn }} -m {{ admin_email }} -n --agree-tos 

- name: Cron job for certbot is installed
  cron: 
    minute: "30"
    hour: "2,14"
    job: "/usr/bin/certbot renew" 

- name: nginx has correct ssl_certificate entry (fixed let's encrypt)
  replace:
    path: /etc/nginx/conf.d/tuleap.conf
    regexp: 'ssl_certificate\ .*'
    replace: '    ssl_certificate             /etc/letsencrypt/live/{{ tuleap_fqdn }}/fullchain.pem;'

- name: nginx has correct ssl_certificate_key entry (fixed let's encrypt)
  replace:
    path: /etc/nginx/conf.d/tuleap.conf
    regexp: 'ssl_certificate_key .*'
    replace: '    ssl_certificate_key         /etc/letsencrypt/live/{{ tuleap_fqdn }}/privkey.pem;'

- name: Testing nginx configuration
  command: nginx -t
  register: testresult

- name: Reloading nginx
  service:
          name: nginx
          state: reloaded




