---
# Tuleap handlers

- name: site-deploy
  shell: tuleap-cfg site-deploy

- name: restart apache
  systemd: 
    name: httpd
    state: restarted

- name: restart nginx
  systemd: 
    name: nginx 
    state: restarted

- name: restart tuleap
  systemd: 
    name: tuleap 
    state: restarted

- name: restart postfix
  systemd: 
    name: postfix 
    state: restarted

- name: reload firewall
  systemd: 
    name: firewalld
    state: reloaded

- name: restart mysql
  systemd: 
    name: rh-mysql57-mysqld
    state: restarted