---
# Tuleap handlers

- name: forgeupgrade
  shell: /usr/lib/forgeupgrade/bin/forgeupgrade --config=/etc/tuleap/forgeupgrade/config.ini update

- name: run.php
  shell: /usr/share/tuleap/tools/utils/php73/run.php --module=nginx

- name: site-deploy
  shell: tuleap-cfg site-deploy

- name: restart apache
  systemd: 
    name: httpd
    state: restarted

- name: restart nginx
  systemd: 
    name: nginx 
    state: restarted

- name: restart tuleap
  systemd: 
    name: tuleap 
    state: restarted

- name: restart postfix
  systemd: 
    name: postfix 
    state: restarted

- name: reload firewall
  systemd: 
    name: firewalld
    state: reloaded

- name: restart mysql
  systemd: 
    name: rh-mysql57-mysqld
    state: reloaded